baseurl = "https://ma.ssive.co/"
languageCode = "en-us"
title = "Ma.ssive"

theme = "casper"

Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  cover = "cover.jpg"
  googleAnalyticsUserID = ""
  githubName = "massiveco"
  hideHUGOSupport = true